server:
  port: 8081

person:
  name: 张珊
  birthday: 1990/09/10
  dog:
    name: 旺财
    age: 1
  friends:
    - 张柳
    - 赵琦
  family:
    mother: 海燕
    father: 海坤

mysql: 
  user-name: root
  password: qds55344679
  url: jdbc:mysql://localhost:3306/db_diary?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
  driver-name: com.mysql.cj.jdbc.Driver 
